# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePin',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Pin')),
                ('image', models.ImageField(height_field=b'image_height', upload_to=b'image-pin/images', width_field=b'image_width')),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False)),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False)),
                ('thumbnail', models.ImageField(blank=True, editable=False, height_field=b'thumbnail_height', upload_to=b'image-pin/thumbnails', width_field=b'thumbnail_width')),
                ('thumbnail_width', models.PositiveIntegerField(blank=True, editable=False)),
                ('thumbnail_height', models.PositiveIntegerField(blank=True, editable=False)),
            ],
            bases=('core.pin',),
        ),
    ]
