# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepin',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, height_field=b'thumbnail_height', null=True, upload_to=b'image-pin/thumbnails', width_field=b'thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='imagepin',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='imagepin',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
